
# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist:
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 7

homebrew_installed_packages:
  - autoconf
  - awscli
  - figlet
  - git
  - go
  - lolcat
  - openssl
  - terraform
  - wget
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - visual-studio-code
  - vagrant
  - font-hack-nerd-font

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode (15.0.1)" }
  - { id: 1295203466, name: "Microsoft Remote Desktop (10.9.4)" }
  - { id: 1298486723, name: "FileZilla Pro (3.65.1)" }

mas_email: ""
mas_password: ""