---
# downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_macos: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
#- Launch Pad
# - TV
# - Podcasts
# - 'App Store'

dockitems_persist:
  - name: "Zen Browser"
    path: "/Applications/Zen Browser.app/"
    pos: 5
  - name: "Ghostty"
    path: "/Applications/Ghostty.app/"
    pos: 6
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 7
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8
  #- name: "VirtualBox"
  #  path: "/Applications/VirtualBox.app/"
  #  pos: 9
  #- name: "Discord"
  #  path: "/Applications/Discord.app/"
  #  pos: 10

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/maccracken/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/Repos/dotfiles"
dotfiles_home: "~"
dotfiles_folders: []
  #- zsh
  #- git
dotfiles_files:
  - .testtmp
  #- .macos

homebrew_installed_packages:
  - autoconf
  - awscli
  - bat
  - btop
  - eza
  - figlet
  - fzf
  - git
  - go
  - lolcat
  - fastfetch
  - node
  - npm
  - openssl
  - starship
  - rbenv
  - rust
  - terraform
  - tmux
  - tpm
  - wget
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - amethyst
  - devtoys
  #- discord
  - docker
  - dockutil
  - ghostty
  - obsidian
  - vagrant
  - virtualbox
  - visual-studio-code
  - zen-browser

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode (15.0.1)" }
  - { id: 1295203466, name: "Microsoft Remote Desktop (10.9.4)" }
  - { id: 1298486723, name: "FileZilla Pro (3.65.1)" }
  - { id: 425424353, name: "The Unarchiver (4.3.6)" }

mas_email: ""
mas_password: ""

macos_script: "~/.macos --no-restart"

terminal_fonts:
  - {name: 'Caskaydia Mono NFM Regular', repo: https://github.com/eliheuer/caskaydia-cove/raw/refs/heads/master/fonts/ttf/CaskaydiaCove-Regular.ttf }
  - {name: 'Caskaydia Mono NFM Bold', repo: https://github.com/eliheuer/caskaydia-cove/raw/refs/heads/master/fonts/ttf/CaskaydiaCove-Bold.ttf}
  - {name: 'MesloLGS NF Regular.ttf', repo:  https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf }
  - {name: 'MesloLGS NF Bold.ttf', repo:  https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf }
  - {name: 'MesloLGS NF Italic.ttf', repo:  https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf }
  - {name: 'MesloLGS NF Bold Italic.ttf', repo:  https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf }

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 2.4.21" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
