homebrew_installed_packages:
  - autoconf
  - awscli
  - figlet
  - git
  - go
  - lolcat
  - openssl
  - terraform
  - wget
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - iterm2
  - visual-studio-code
  - vagrant
  - font-hack-nerd-font