---
# downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
# configure_macos: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist:
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 5
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 6
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 7
  - name: "VirtualBox"
    path: "/Applications/VirtualBox.app/"
    pos: 8

dotfiles_repo: https://github.com/maccracken/dotfiles.git
dotfiles_repo_version: main
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: "~/.dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .aliases
  - .functions.zsh
  - .gitconfig
  - .p10k.zsh
  - .zshrc
  - .figlet/fonts/modular.flf
  # - .inputrc
  # - .macos
  # - .vimrc

homebrew_installed_packages:
  - autoconf
  - awscli
  - figlet
  - fzf
  - git
  - go
  - lolcat
  - node
  - npm
  - openssl
  - powerlevel10k
  - ruby
  - terraform
  - wget
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - font-hack-nerd-font
  - iterm2
  - obsidian
  - vagrant
  - virtualbox
  - visual-studio-code

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode (15.0.1)" }
  - { id: 1295203466, name: "Microsoft Remote Desktop (10.9.4)" }
  - { id: 1298486723, name: "FileZilla Pro (3.65.1)" }

mas_email: ""
mas_password: ""

macos_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages:
  - name: colorls
    state: present
    version: "~> 1.4.6"
#gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 2.4.21" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A
