---
- name: Configure host
  hosts: all

  vars_files:
    - default.config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: maccracken.macos-dmg-install
      vars:
        - appName: Obsidian
        - dmgURL: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.4.16/Obsidian-1.4.14-universal.dmg
      tags: ['obsidian']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    # - import_tasks: tasks/sudoers.yml
    #   when: configure_sudoers
    #   tags: ['sudoers']

    # - import_tasks: tasks/terminal.yml
    #   when: configure_terminal
    #   tags: ['terminal']

    # - import_tasks: tasks/macos.yml
    #   when: configure_macos
    #   tags: ['macos']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']