---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: maccracken.dotfiles
    src: ssh://git@github.com/maccracken/role-dotfiles.git
    version: main
    scm: git

collections:
  - name: geerlingguy.mac